GET http://localhost:3001/getMedicine HTTP/1.1

###

POST http://localhost:3001/createMedicine
Content-Type: application/json 
{
    "name":"pepcid",
    "dosage": "3",
    "time":"1:30",
}

###
DELETE http://localhost:3001/deleteMedicine/64d111df8756e282738d9d58